### ISSUE TITLE
Themes

### ISSUE THREAD

**Issue by Gerold55** [Gerold55/minetest-laptop#102]
Should we be able to make the icons customizable like the other things of the theme?

Last-To-Do List
 - [x] for chest game we can set os_min_version to a value higher then the monochrome versions.
 - [x] All other themes needs to be tested and adjusted for new parameters.
 - [x] I try to merge our and my branch, then I add "monochrome" parameter and adjust tetris to colorize all by the cs-bos console textcolor in this case
- [x] replace default_diamond_block.png in tetris app by own "gray" texture
 - [x] Please change/rename also theme.bgcolor2 to something prefixed (theme.second_bgcolor ?)-  EDIT: they are textures, so name both bgcolor to _background. bgcolor is reserved for rgb-values
- [x] adjust default bgcolor rgb values and port more unicolor textures to mtos.theme:get_bgcolor_box()
- [x] Check texture filename prefixes for "laptop_*.png". Check unused textures could be deleted
- [x] Check/Update API.md documentation
- [x] Check/Update the README.md
- [x] Clarify if tty_monochrome should be setteable by theme (ember and green theme)

**Comment by Gerold55** [comment]
@grizzly-Adam if I send you some pics of a new theme created by CrossZover could you implement them for me?

**Comment by Grizzly-Adam** [comment]
I think that would be a good option for future. 

Yes, I can impliment them as soon as bell releases the cs-bos update. I dont want to delay it any further.

**Comment by Gerold55** [comment]
Ok because @CrossZover has 2 new plain red and blue themes ready. Also a new PCPack is being worked on.

**Comment by Grizzly-Adam** [comment]
Oh! Can I make a couple suggestions for the new PC pack?

**Comment by Gerold55** [comment]
I'll send them tonight after I'm done working

**Comment by Gerold55** [comment]
@Grizzly-Adam do you have a business email so I can send them to you?

**Comment by Grizzly-Adam** [comment]
Just send to my personal. I will PM you on mt.

**Comment by bell07** [comment]
I did the tables themeable too
```
- `table_background` - Table background color
- `table_color` - Table text color
- `table_highlight` - Table highlighted background
- `table_highlight_text` - Table highlighted textcolor
- `table_border` -  draw border (true or false)
```

@Gerold55,  @Grizzly-Adam, can you please propose values for "Default/Freedom" theme and may adjust existing themes?
See my [pr_tables_theming](https://github.com/bell07/minetest-laptop/tree/pr_tables_theming) branch.

I set  currently as demo-values:
```
		table_background='#000000',
		table_color='#FFFFFF',
		table_highlight='#FFFF00',
		table_highlight_text='#0000FF',
		table_border='false',
```

**Comment by Grizzly-Adam** [comment]
I am working late today, got a door tech here. Will try them layer if I get out soon.

**Comment by Grizzly-Adam** [comment]
I have been working on skinning the mail program and was planning to ask you for more theme options to make it all work. I will try these ones and let you know if I need any more fields added (I was thinking something similar to the contrast colors, but with the main theme color (just not tied to other attributes).
Anyway, I will work on it and let you know what I need

Sorry guy, I didn't get a lot done but I got out of work several hours late tonight.

**Comment by Grizzly-Adam** [comment]
Is it still possible to override CS-BOS text color when registering hardware? I have a computer running 1.10 that I would like to give a monochrome green monitor.

**Comment by bell07** [comment]
At the time - no.  But I can implement it. It does sense since this color is more depending on hardware then on software version..

**Comment by bell07** [comment]
I removed my branched and pushed all my new changes to my master: https://github.com/bell07/minetest-laptop

For more systematic attribute names shema I renamed the table parameters to:
```
- `table_bgcolor` - Table background color
- `table_textcolor` - Table text color
- `table_highlight_bgcolor` - Table highlighted background
- `table_highlight_textcolor` - Table highlighted textcolor
- `table_border` -  draw border (true or false)

```

Can you please provide the default values to me or set up a branch that I can merge?

which theming option do you like to have in addition? Let me know so I can implement it as I find time.


> I was thinking something similar to the contrast colors, but with the main theme color (just not tied to other attributes)

This should be simple as the "prefixes" does work generic

Example: new prefix "abc"
you set an `abc_button = "laptop_abc_button.png"` and `abc_textcolor = "#123456"`
you can use `theme:get_button('x,y;w,h', 'abc', code, text)` theme:get_label('x,y', text, 'abc')

They are two challanges:
- find a meaningfull name for "abc"
- find default values for Freedom theme - as the default theme should be allways complete because elements used as fallback in other themes


> Is it still possible to override CS-BOS text color when registering hardware? I have a computer running 1.10 that I would like to give a monochrome green monitor.

I added the option hwdef.tty_style, so you can set the tty_style='AMBER', tty_style='GREEN' or tty_style='WHITE' to the hardware definition.
If you need more colors, you need to add new colors to "supported_textcolors" table in cs-bos_app.lua file, or provide the value to me

**Comment by bell07** [comment]
Added support for textures replacement in themes:
You can define in theme now 
```
	texture_replacements = {
		['laptop_email_trash.png'] = 'laptop_themed_trash.png',
	}
```
to replace the email trash button icon if an theme is selected.

works with all theme:get_image_button() (all buttons in mail_app) and if the new method theme:(get_texture) is used (bomb or boom in TNTSweeper). Should be complete, if something missed, let me know. The tetris is difficult because additional texutre colorization is used.

**Comment by bell07** [comment]
added support for texture_replacements in launcher to replace the app icons...

**Comment by bell07** [comment]
> Should we be able to make the icons customizable like the other things of the theme?

this is done by texture_replacements support mentioned above

In my [more_theming_support](https://github.com/bell07/minetest-laptop/tree/more_theming_support) branch. The changes could be merged if the tables theming support is finished (Themes adjustment needed to use the new colorizing parameters)

**Comment by bell07** [comment]
added some table colors to themes. @Grizzly-Adam , please check if the colors does match your imagination

**Comment by Grizzly-Adam** [comment]
Thanks bell07, I will take a look. I am hoping that I can concentrate well enough to fully evaluate it. I am returning to work tomorrow.

**Comment by Grizzly-Adam** [comment]
@bell07 Give me two more things and I theme I can fully skin the apps to match the themes (except for app specific buttons).

I need:
muted_textcolor (a text color that can be used for things like read mail)
theme_background or uniform_background (a background that is complimentary to the theme-- opposite of contrast background).

**Comment by bell07** [comment]
ok, new prefix "muted"
and value "bgcolor" global or prefixed. "background" is used already for background texture, so the background color is "bgcolor" as I introduced for tables

**Comment by bell07** [comment]
@Grizzly-Adam do you need support you to add the required things?

You need just to add default values for "muted_textcolor" to "bgcolor" to the default theme "Freedom" in themes.lua, then to the other themes if differ. In code you can access the values by "mtos.theme.muted_textcolor" and "mtos.theme.bgcolor" or using prefix in theme:get_* methods.

> (except for app specific buttons).

This is possible too with my last changes. Just define in theme
```
laptop.register_theme("???", {
	desktop_background = 
...
	texture_replacements = {
		['laptop_email_trash.png'] = 'laptop_themed_trash.png',
		['original.png'] = 'themed.png',
	}
})
```

**Comment by bell07** [comment]
By the way, I am unhappy with "Freedom" as technically fallback theme. The fallback should not be green. The most themes needs to override most values because not green.
My proposal is to move the "Freedom" to own file like the other themes, and then define hidden "default" theme with settings as used in the most themes., then redundancy could be removed from other themes.
The "Freedom" can be still hardcoded as default theme if no theme selected.

**Comment by Grizzly-Adam** [comment]
I agree, we need something with the typical blues and greys. Either a new basic theme, or use the clouds theme.

**Comment by bell07** [comment]
Are you working on skins colors adjustments? If not I can consolidate the default theme and degrade the Freedom to "usua"l theme in the evening. "default" is hidden hard-coded so it will be really fallback-only definition, with background image = "" and so

**Comment by Grizzly-Adam** [comment]
I am not currently. Go ahead and make your changes and I will start after work.

**Comment by bell07** [comment]
I done the split of freedom from fallback values and removed all fallback redundancies. [more_theming_support](https://github.com/bell07/minetest-laptop/tree/more_theming_support) 
@Grizzly-Adam you can take over again to adjust the themes. If you miss something, just add it or ask me ;-) I think using texture_replacements and the table-colors it is able now to get nearly full monochrome output for old computers

**Comment by Grizzly-Adam** [comment]
I will work on the buttons tomorrow. See screenshots. Can green/black menu  in screenshot 1 be changed to match theme?

Can message text area in screenshot 3 be bordered?


![screenshot from 2018-03-12 19-10-37](https://user-images.githubusercontent.com/35204361/37315948-6206e28e-262a-11e8-8aed-c03db1d09c63.png)
![screenshot from 2018-03-12 19-16-11](https://user-images.githubusercontent.com/35204361/37315949-6224d230-262a-11e8-9bd9-cedb476b3cda.png)
![screenshot from 2018-03-12 19-17-08](https://user-images.githubusercontent.com/35204361/37315950-62447504-262a-11e8-80c1-9977916d8c59.png)

**Comment by bell07** [comment]
> Can green/black menu in screenshot 1 be changed to match theme?

maybe (needs to be tested) we can change the text color by colorizing the text string using minetest.colorize(color, string)`, but no idea how to theme the green bar and background in dropdown :-(
We have some other not colorizable elements like scrollbars :-(

By the way, I found in [lua_api.txt](https://github.com/minetest/minetest/blob/backport-0.4/doc/lua_api.txt) the formspec
> #### `box[<X>,<Y>;<W>,<H>;<color>]`
> * Simple colored semitransparent box
> * `x` and `y` position the box relative to the top left of the menu
> * `w` and `h` are the size of box
> * `color` is color specified as a `ColorString`

Maybe we can remove all "1-color-backgrounds" and replace them by this command? So we can remove some texture files? I write the theme:get_background(texture or rgb) method to be able to use both, texture and color in "background" settings.

**Comment by Grizzly-Adam** [comment]
Sorry, I missed this one earlier. That sounds like a great idea. All the 1x1 pixel images are a pain!

**Comment by bell07** [comment]
Yea, and the "contrast_background" can be "migrated" to contrast_bgcolor ;-)

I am working on method `theme:get_bgcolor_box(area, prefix)` with tech-demo in "file selection dialog"..

**Comment by Grizzly-Adam** [comment]
What am I doing wrong, buddy? (This isn't the fully theme, but enough to show you how I am using the new code. Many lines removed between app_background and texture_replacement.
```
laptop.register_theme("Amber Shell", {
	desktop_background = "laptop_theme_ambershell_desktop_background.png",
	app_background = "laptop_theme_ambershell_app_background.png",
	texture_replacements = {
		['laptop_mail.png'] = 'laptop_theme_ambershell_mail.png',
		['laptop_email_letter_new.png'] = 'laptop_theme_ambershell_email_letter_new.png',
	}
})
```

**Comment by bell07** [comment]
Looks right. What is the issue?

**Comment by bell07** [comment]
Done the theme:get_bgcolor_box(area, prefix): https://github.com/bell07/minetest-laptop/commit/1feeddf108cf62cf67fae62f7d36fd079fd80664
You can see in commit how to use and which themes parameter could be used.I re-used existing prefixes. The idea is the bgcolor should match the prefix-background texture basecolor.

app_bgcolor is the base color of app-background for example (white).
Please modify the default values to more meaningful. I just set some values for demo reasons.

You can checkout my more_theming_support branch or just learn about `git cherry-pick` ;-)

**Comment by Grizzly-Adam** [comment]
I am not seeing the texture_replacements is not showing up in the theme.

**Comment by bell07** [comment]
> What am I doing wrong, buddy?

I see your issue ;-) not all png files does support the replacing. For example laptop_mail.png and laptop_mail.png and laptop_mail_read.png

`"image,align=center,1=laptop_mail.png,2=laptop_mail_read.png;"..`

To support them the line should be 

`"image,align=center,1="..mtos.theme:get_texture('laptop_mail.png')..",2="..mtos.theme:get_texture('laptop_mail_read.png')..";".. `

I did not adjusted all textures.  Only the get_image_button() method that is used for most buttons in mail app.

**Comment by bell07** [comment]
laptop_email_letter_new.png is not used in app. The app icon is laptop_email_letter.png

Therefore:
`['laptop_email_letter.png'] = 'laptop_theme_ambershell_email_letter_new.png',`

**Comment by Grizzly-Adam** [comment]
Oh. I thought it was the one in the message lift on the left side.

**Comment by Grizzly-Adam** [comment]
OK great, I got the above changes you mentions and now am working on more themed textures for the buttons. I will let you know when I get all of the amber shell done for the mail program and get your opinion.

**Comment by Grizzly-Adam** [comment]
OK, these two apps are looking pretty good, except the green tooltips and the green dropdown screen we discussed earlier.

![screenshot from 2018-03-13 19-53-51](https://user-images.githubusercontent.com/35204361/37377840-5351b676-26fa-11e8-9502-6a0f95c9c1d6.png)
![screenshot from 2018-03-13 20-05-04](https://user-images.githubusercontent.com/35204361/37377841-537bc16e-26fa-11e8-918a-0d31da451a32.png)

**Comment by Grizzly-Adam** [comment]
@apachano @Gerold55 What do you guys think of the buttons in the mail screenshot and the fire in the tnt sweeper screenshot? I need to convert to green yet, but want to make sure the work is acceptable before I do so.

**Comment by Gerold55** [comment]
I think they look great @Grizzly-Adam

**Comment by Grizzly-Adam** [comment]
@bell07 I could not figure out how to get mtos themes to work with the chess pieces and the printer online color. Could you please advice-- I am assuming that it is due to mtos not being called in functions but am not sure how to properly call it.

**Comment by Grizzly-Adam** [comment]
Shell icons done.

![shell](https://user-images.githubusercontent.com/35204361/37440112-586c28ce-27c9-11e8-9a64-825cdda1cc0d.png)

**Comment by bell07** [comment]
> mtos themes to work with the chess pieces and the printer online color.

chess pieces are registered technically as items. There is no way to change the texture for items. 

The printer colors could be themed as next:

Add the current values to the default theme called as status_online_textcolor, status_disabled_textcolor and status_off_textcolor. The values could be useful in other apps too.

Then you can remove the colors defined in `local function get_printer_info(pos)`. We are able to get it dynamically by `"status_"..printer.status.."_textcolor"`

The printer online color is defined in https://github.com/Gerold55/minetest-laptop/blob/master/apps/os_print_app.lua#L221
`minetest.pos_to_string(printer.pos)..' '.. minetest.colorize(printer.status_color,printer.status))`

replace `printer.status_color` by `mtos.theme["status_"..printer.status.."_textcolor"]`

Done

PS: you get the next issue in theming the tetris app, because of hard-coded colorizing. I think we need a "monochrome = true" parameter to skip colorizing. But then all bricks looks the same..

**Comment by Grizzly-Adam** [comment]
OK, that just leaves the Tetris issue, and the chess that we can do nothing about. Maybe we set chess to not run on monochrome monitors?

**Comment by bell07** [comment]
OK, for chest game we can set os_min_version to a value higher then the monochrome versions.
All other themes needs to be tested and adjusted for new parameters. 
I try to merge our and my branch, then I add "monochrome" parameter and adjust tetris to colorize all by the cs-bos console textcolor in this case

**Comment by bell07** [comment]
Please change/rename also theme.bgcolor2 to something prefixed (theme.second_bgcolor ?)
I strart a"last-to-do" list in the first post

**Comment by bell07** [comment]
ok, I set the os_min_version for realchess and adjusted the framework + tetris app for monochrome output.
By the way, The default_diamond_block.png in tetris app needs to be replaced by own texture. Own texture should be gray, because colorized in lua.

Both changes are in pull request to your repo, @Grizzly-Adam

**Comment by Grizzly-Adam** [comment]
I will make some progress with this tomorrow. Just got home from work and I am exhausted. Not sure why.

**Comment by bell07** [comment]
Tried to replace the "bgcolor1" image by `mtos.theme:get_bgcolor_box('8,1.55;6.9,7.2', "table")..`
Does not work for amber theme and I do not have an idea why :-(

By the way, the Amber theme is not used in this mod. Can we setup the green and amber theme to be useable up to 5.50 version? So the themes will be selectable for nostaliga fans on "cube" and "portable workstation"?

**Comment by Grizzly-Adam** [comment]
Amber theme is used for computers who's monitors are only amber, same with the green theme. If we want to allow it to work on 5.50 it will mean chess needs min version of 5.51. I will have to monochrome the setting icon too (not a big deal). It can be done if that's what you want. I'm ok either way.

**Comment by Grizzly-Adam** [comment]
I am really happy with how the tetris texture turned out.  Looks good in amber, green and in color.
![screenshot from 2018-03-17 10-44-29](https://user-images.githubusercontent.com/35204361/37557305-84c5fad6-29d0-11e8-833f-b06eaf34976c.png)

**Comment by Grizzly-Adam** [comment]
@bell07 
re: Please change/rename also theme.bgcolor2 to something prefixed (theme.second_bgcolor ?)- EDIT: they are textures, so name both bgcolor to _background. bgcolor is reserved for rgb-values

How about theme.background and theme.alt_background. And you are the one who named the bgcolor to begin with :P

**Comment by Grizzly-Adam** [comment]
I looked all the themes over, made some adjustments (mainly to table colors and textcolor). Amber theme is complete, green theme is now done as well. Improved background on CS-BOS Shell theme. Made all shell themes max_os_version 5.5 max, chess 5.51 min.

**Comment by Grizzly-Adam** [comment]
@Gerold55 Here is my attempt at sprucing up the printer screen. Looking for input.

![screenshot from 2018-03-17 17-46-35](https://user-images.githubusercontent.com/35204361/37560752-35a23b40-2a0c-11e8-8b23-8cce15e5e0fd.png)

**Comment by Gerold55** [comment]
Looks pretty good 👍

**Comment by bell07** [comment]
> How about theme.background and theme.alt_background. And you are the one who named the bgcolor to begin with :P

I see we are confused both on the lot of new settings :P 
Let consolidate the existing prefixes:

desktop - Launcher Setting (Background only)
desktop_icon - Background for app icon in launcher
desktop_icon_label - THe label under app icon in launcher
app - setting for App Window (Background)
titlebar - The title bar in App window
back - App window back button
exit - App window Exit button
major - Highlighted (Button)
minor - Not highlighted (Button)
muted - ??
contrast  - Dark area under not themeable elements
table - Table colorizing
table_highlight - "The green bar" - highlighted table colorizing
status_online - "green"
status_disabled - "yellow"
status_off - "red"


Do you see prefixes we can consolidate? Maybe app, major, minor or muted could be re-used?

I think "Label-Textarea" shoud be themed in same way as the table. So the bgcolor1 is "table_background" (The background image is the same color as table_bgcolor RGB value)

What is the reason for bgcolor2? Do we need new "alt" prefix or we can re-use existing one?

**Comment by Grizzly-Adam** [comment]
Looks in the mail app for the use of bgclolr2 (now alt_background). I
needed two background colors in there-- I think it was for the right
"message" payne.

**Comment by bell07** [comment]
I see some textures are named wrong. All textures needs to be named "laptop_" to avoid overwrites by other mods.
printer_button.png
printer_button1.png (unused?)
printer_printed.png (unused?)
tetris_block.png

> I looked all the themes over, made some adjustments (mainly to table colors and textcolor).

Can you please push the changes for review?

I checked the PNG-files, the next of them seems to be not used:
laptop_calendar.png
laptop_email_letter_new.png
laptop_email_trash_B.png
laptop_m_bios.png
laptop_manual.png
laptop_theme_ambershell_mail.png
laptop_theme_greenshell_mail.png
laptop_txt_document.png
printer_button1.png
printer_printed.png

**Comment by Grizzly-Adam** [comment]
I will double check all these files tonight and send the push.

**Comment by Grizzly-Adam** [comment]
I deleted all the mentions files from my install and found no issue. Lets hang onto calendar, bios, manual, and text document (maybe place them in their own repository or something) because we will probably use them later.

Renamed tetris_block.png and printer_button.png. Updated tetris & mail apps,  full colour, amber and green shell themes to reflect these changes.

Update pushed.

**Comment by bell07** [comment]
Thank you! I checked all and seems to be fine.

About tetris monochrome theming: I tired the ember theme on CUBE since it is selectable. In tetris the blocks are colorized, because the "tty_monochrome" setting is set in OS version and HW-node, the Cube both does not match. What do you think, should be the "tty_monochrome" setteable on theme too? So tetris will be monochrome on "more modern" devices if ember or green theme selected. (I vote for yes, can do it in evening)

Created new branch to store unused textures: https://github.com/Gerold55/minetest-laptop/tree/unused_textures

The last point is to check README, and API doc if all new things are mentioned. I do rewrite the theming documentation in API, grouped by prefixes in evening

**Comment by Grizzly-Adam** [comment]
Yes, theme should set tty to make sure our apps all looks the way we intend
them to.

**Comment by Grizzly-Adam** [comment]
The more I thinl about it the better setting tty through theme sounds. It will mean color is no longer tied to os version and we can make any old computer amber, green, or full color regardless of version.

I looked at the reqdme last night and didnt find anything that needed updating.

**Comment by bell07** [comment]
Note we have 2x tty settings:

 1. tty_textcolor - Initially OS-version dependant, but can be set differ for each hardware ("AMBER", "GREEN", "WHITE")
2. tty_monochrome - Boolean setting if the colors could be changed or not. Used in CS-BOS to disable "TEXTCOLOR" command, and in tetris-app to disable blocks colorizing.


I had the idea to merge tty_textcolor with themes "table_textcolor". But the tty_textcolor value is not RGB and needs to be supported by CS-BOS "TEXTCOLOR" command.

I am about tty_monochrome setting. In CS-BOS the OS-Version and HW setting still should be used, for tetris app the setting should be used from theme ("optimized for monochrome")

**Comment by bell07** [comment]
Introduced theme.monochrome_textcolor is set in both monochrome themes and used in tetris app. This attribute means "theme optimized for monochrome".
Idea happens some other textures could be colorized same way as tetris shape, so we could use gray textures instread of green or amber (needs to be consolidated, maybe next development iteration)

Rewrote the API.md theming area: https://github.com/bell07/minetest-laptop/blob/more_theming_support/API.md#themes

Still unhappy with nex prefixes (not in API.md).
Note: Each prefix can have textures _background and _button, and colors _bgcolor, _textcolor.

Introducing get_bgcolor_box() I added bgcolors to "major" / "minor" / "contrast". Looked to "Save as" dialog.

		app_background -  the "default" app background (white) (prefix "app")

		alt_background -  Underlay under table - prefix "alt" - > should it be prefix table (table_background?)

		background - prefix-less is implemented as fallback. Which idea is in mail app for this texture? Maybe it should be "app" or an other prefix?

P prefer to reduce the count of used prefixes to avoid redundancies

**Comment by Grizzly-Adam** [comment]
I used background, contrast_background, and alt_background in mail. All
image files. You already have app_background to make the title bar. Ideally
I woukd like it if we could use codes for all the colors. A lot of our
prefixes come from the need for both background and bgcolor.

**Comment by bell07** [comment]
I see the app_background is not usable because of title bar. 
can you propose which prefix have which meaning and which of them are maybe redundant and coul be removed?
: major, minor, app, alt, table, muted

We need an explanation for all prefixes, the API should be understandeable for the case a new developer needs to write a fully new theme, the settings meaning should be predictable. Of course all elements was added on need, I try to consolidate them after is known what is needed :-)

"background" needs to be prefixed. I think the "fallback" values without prefix should be removed, (background, bgcolor, textcolor) because irritated.

**Comment by Grizzly-Adam** [comment]
Let me look at the code of mail app when I get home. Maybe major/minor can
work for other things.

**Comment by bell07** [comment]
I did some more consolidation. See my branch / PR to your repo:

  1. I disabled/removed fully the alt_background, did not seen any difference. Tested on greenshell (black vs. black) and on cubic (white vs. grey) and some other themes. 
I do not like the idea for second background over the app_background. If anything needed, the app_background needs to be adjusted, or other elements added.

  2. in mail app now the "table_background" instread of "background". Thesetting it is related to the table set (should be always the same color as RGB bgcolor?)

  3. Removed minor_bgcolor and major_bgcolor (was tech demo for get_bgcolor_box()). Use now the "contrast" and "table_highlight" prefixes in "Save as" dialog.

  4. Updated the API again, reordered settings in default theme (themes.lua) to match the API order

  5. The Ambershell and Greenshell does have the bright color for contrast. The contrast is for "white texts in edit fields" so it should be dark per definition. Can we change them to something more dark?

**Comment by bell07** [comment]
> We don't use anything with the app prefix except app_background,. Maybe fold that into major?

the meaning content does not match. But maybe the titlebar_textcolor should be "app_textcolor"? Or we should split the background to 2x images: the titlebar and the background? Maybe next iteration, I tink we should finalize the work.

> I have tried setting this as dark, but it looks awful because you just end up with a nearly black screen with text that has been tinted not quite the right color. Looks way better orange/green with dark text. 

The "contrast" prefix is for "dark background to place under white text elements that does not support textcolor". Of course it looks beter with dark text on orange/green, but not always possible.
The contrast image was used on some other places too, therefore we added "contrast_textcolor" (some labels are placed on contrast background. This color is used to colorize them)

The Print app is a good example.
Ok, the big text preview area I can theme now to "table" since it is not editable, but the "Heading" input field not, therefore the texture under them needs to be dark. The "Heading" label is "contrast_textcolor"

Other screens that needs attention for contrast images are the Text editor, New Mail view, Save as does have filename input fields

**Comment by bell07** [comment]
Applied the "table" theming to the preview in printer app. Changed the Heading underlay to get_bgcolor_box("","contrast"), and Heading text to "contrast_textcolor" that is amber now in amber theme.
![image](https://user-images.githubusercontent.com/4731334/37696193-305a3d06-2cd5-11e8-934d-9c97ed8a74d1.png)



The table_background under text areas looks strange on themes using "table_border". Maybe you can create new textures for with 1x Pixel border for such "table_background"?

![image](https://user-images.githubusercontent.com/4731334/37696160-ef758d90-2cd4-11e8-85fd-87bbdce14802.png)

**Comment by Grizzly-Adam** [comment]
Yeah, I can do that. I would like to have a border on the right payne of
the mail app too.

**Comment by bell07** [comment]
The mail app uses the same logic for text area is themed using table prefix ("table_background"). So it should work out of the box for mail, if it does work for print file.
I fear the border line scaling issues because of different area sizes :-(

**Comment by Grizzly-Adam** [comment]
I have several 1x1 images in the textures fokder, grab one of them and see
uf it works. I plan to rename all the 1x1s so they have aimilar names and
are more available to all themes-- also will be easier to purge them all
should we no longer need them.

**Comment by bell07** [comment]
```
$ file textures/* | grep '1 x 1'
textures/laptop_theme_ambershell_desktop_icon_label_button.png: PNG image data, 1 x 1, 8-bit/color RGB, non-interlaced
textures/laptop_theme_boing_major_button.png:                   PNG image data, 1 x 1, 8-bit/color RGB, non-interlaced
textures/laptop_theme_clouds_desktop_icon_label_button.png:     PNG image data, 1 x 1, 1-bit colormap, non-interlaced
textures/laptop_theme_colors_light_grey.png:                    PNG image data, 1 x 1, 8-bit/color RGB, non-interlaced
textures/laptop_theme_desktop_icon_label_button_black.png:      PNG image data, 1 x 1, 1-bit colormap, non-interlaced
textures/laptop_theme_desktop_icon_label_button_darkblue.png:   PNG image data, 1 x 1, 8-bit/color RGB, non-interlaced
textures/laptop_theme_desktop_icon_label_button_grey.png:       PNG image data, 1 x 1, 1-bit colormap, non-interlaced
textures/laptop_theme_desktop_icon_label_button_white.png:      PNG image data, 1 x 1, 1-bit colormap, non-interlaced
textures/laptop_theme_greenshell_desktop_icon_label_button.png: PNG image data, 1 x 1, 8-bit/color RGB, non-interlaced
textures/laptop_theme_shell_desktop_icon_label_button.png:      PNG image data, 1 x 1, 8-bit/color RGB, non-interlaced

```
What do you mean I should test if works? All of them are used as "buttons" textures.

I checked all of them, the next are not used:
  - laptop_theme_colors_light_grey.png
  - laptop_theme_desktop_icon_label_button_darkblue.png

used only for table_color => can be converted to bigger texture with border
  - laptop_theme_desktop_icon_label_button_white.png



Did you tried the borders for "table_background" images?

**Comment by Grizzly-Adam** [comment]
I read your post wrong, I thought you were going to use a 1x1 pixel image
to make the border. I assumed you would do a top, bottom, left, and right
images as the lines for the border. Now I understand that is not what you
meant.

**Comment by bell07** [comment]
Found a beter way to solve the border problem: A empty themed table instead of background images.
Implemented, see my branch / the PR in your repo.

Removed again the "table_backgrounds" setting and not used textures
 - laptop_theme_colors_light_grey.png, 
 - laptop_theme_desktop_icon_label_button_darkblue.png, 
 - laptop_theme_desktop_icon_label_button_white.png

From my point of view all work is done now!
Please review and test the changes if you see something is still missed. If not, we can setup the PR to upstream/master

**Comment by Grizzly-Adam** [comment]
If I get the chance I will check PR tonight, test and issue pr to maon
build tonight. But I wobt be home until late so it may have to wait until
tomorrow.

**Comment by bell07** [comment]
Ok, I changed back the "contrast" to amber/green in the both themes. Previously some parts (Write mail screen for example) was colorized using contrast_bgcolor/contrast_textcolor as I expected, but looks not nice.
No rule without exception, the both monochrome themes uses bright background for not themeable white text. Looks beter but more exhausting to read. Like the old monitors ;-)

If you merges my both commits to your branch we can merge them

**Comment by bell07** [comment]
All Changes merged!
