### ISSUE TITLE
Printers

### ISSUE THREAD

**Issue by Grizzly-Adam** [Gerold55/minetest-laptop#105]
@bell07 I am working on putting together PC Pack2 and it contains a printer (the Benson Data Writer 45). When I scan for printers I get two flash printexes instead of a Flash and a Benson.I think I entered everything properly and am wondering if the OS is currently capable of multiple printers. Also, there theme doesn't show up properly-- perhaps it's unthemed?

See collaged screen image bellow:
![screenshot from 2018-03-01 16-56-05](https://user-images.githubusercontent.com/35204361/36874856-1ebc76a2-1d73-11e8-8f45-c0f6fb61c7b4.png)

```
-----BEGIN BENSON DATAWRITTER 48-----
laptop.register_hardware("laptop_pc2:benson_printer", {
	description = "Benson DataWriter 48",
	infotext = 'Benson DataWriter 48',
	sequence = { "off", "on" },
	custom_launcher = "printer_launcher",
	custom_theme = "Boing!",
	hw_capabilities = {"hdd"},
	node_defs = {
		["on"] = {
			hw_state = "power_on",
			tiles = {
				"printer_top.png",
				"printer_bottom.png",
				"printer_right.png",
				"printer_left.png",
				"printer_back.png",
				"printer_front_on.png"
			},
			drawtype = "nodebox",
			paramtype = "light",
			paramtype2 = "facedir",
			groups = {choppy=2, oddly_breakably_by_hand=2, dig_immediate = 2, laptop_pc2_printer = 1},
			node_box = {
				type = "fixed",
				fixed = {
					{-0.375, -0.5, -0.375, 0.375, -0.3125, 0.375}, -- NodeBox1
					{-0.3125, -0.3125, 0.0625, 0.3125, -0.25, 0.3125}, -- NodeBox2
				}
			       }
			    },
		["off"] = {
			hw_state = "power_off",
			tiles = {
				"printer_top.png",
				"printer_bottom.png",
				"printer_right.png",
				"printer_left.png",
				"printer_back.png",
				"printer_front.png"
			},
			drawtype = "nodebox",
			paramtype = "light",
			paramtype2 = "facedir",
			node_box = {
				type = "fixed",
				fixed = {
					{-0.375, -0.5, -0.375, 0.375, -0.3125, 0.375}, -- NodeBox1
					{-0.3125, -0.3125, 0.0625, 0.3125, -0.25, 0.3125}, -- NodeBox2
				}
			}
		}
	}
})
-----END BENSON DATAWRITTER 48-----
```

**Comment by Grizzly-Adam** [comment]
The theme issue may be on my end. I will check that out tomorrow.

**Comment by bell07** [comment]
Yes, the printer launcher is not fully themed. For labels the theme:get_label() is not used. See "printer_launcher" definition in os_print_app.lua. Can you pls fix it self, or wait till tomorrow. Today I do not have time for laptop.

By the way, I found out why your last changes gets lost on this file, you uploaded the file to root directory but it should be in apps ;-) I did seen new file in change but not realized the file goes to the wrong place. :-(. so the file https://github.com/Gerold55/minetest-laptop/blob/master/os_print_app.lua can be  deleted again;-)

About the scan: the scan look in groups for "laptop_printer". You called the group wrong to "laptop_pc2_printer"

**Comment by Grizzly-Adam** [comment]
Thanks bell, I will see if I cab get this all straightened out tonight.

**Comment by bell07** [comment]
I added the missed theming to the printer launcher. Look to my [pr_printer_theming](https://github.com/bell07/minetest-laptop/tree/pr_printer_theming) branch.
The Printer name above-left uses "titlebar_textcolor", the dye and paper counter are bound on "contrast_textcolor". Ok this assignment?

**Comment by bell07** [comment]
I see the documents table could be themeable too. I like to implement new theme parameter
`tableoptions = "background=#000000;color=#FFFFFF;highlight=#FFFF00;highlight_text=#0000FF;border=false"`

This theming should be compatible to the mail app (mails list) calculator app and "load files", so proposal needed for "Freedom/Default" and other themes

**Comment by Grizzly-Adam** [comment]
OK, that solved the printer scan problem.  Theme for printers looks better. Text in the upper left is black on dark grey, should be white, light grey, or bright green.

**Comment by bell07** [comment]
> Text in the upper left is black on dark grey, should be white, light grey, or bright green.

I see that. Any idea which theme could be used for that? Or is "titlebar_textcolor" attribute wrong and an other should be used Maybe give amber or green theme a try again? Or maybe we need an own "printer theme"?

**Comment by bell07** [comment]
I removed the branch and pushed all my new changes to my master: https://github.com/bell07/minetest-laptop

Please note the tableoptions parameter are renamed as mentioned in https://github.com/Gerold55/minetest-laptop/issues/102#issuecomment-370152065

I removed the "Boing!" theme from printer definition and set the default "Freedom" theme this way. THe titlebar is white now as defined in Freedom, The green-bordered buttons are ok for me. The tableoptions still ugly as defined by me for tech-demo reasons

**Comment by Grizzly-Adam** [comment]
@bell07 Please be advised that my family has suffered a great tragedy today. I will not be contributing much for a while. I will try to remain involved in the project, but probably won't be doing much coding for a while.

**Comment by Gerold55** [comment]
Sorry bout that

Brandon Chaney

**Comment by bell07** [comment]
heartfelt sympathy from my site too (google helped me to find the right words in translator).
Take care of your family. Laptop can wait.
Maybe you can upload the current state even incomplete so we can try to continue your work?

**Comment by Grizzly-Adam** [comment]
All I was working on was skinning the mail program to match theme. I was going to do the same with the other apps once a standard was established. That can all wait.
