### ISSUE TITLE
Mail has to be opened twice

### ISSUE THREAD

**Issue by Grizzly-Adam** [Gerold55/minetest-laptop#112]
Click mail. It doesn't open. Click it again, it opens.

In CS-BOS type mail-- it says mail launched. Type mail again. It opens.

**Comment by bell07** [comment]
I tested it with your master and your master and your more_theming_support branches and cannot get the error.

Maybe broken data in hardware? Can you test again with new fresh computer?  May we need "factory reset" or "FORMAT HDD:" for such reason.

**Comment by Grizzly-Adam** [comment]
I hqve had this ongoing but kept forgetting to report it  I have done
numerous installs but can try a new one again tonight.

**Comment by bell07** [comment]
I get the issue once in a new world with a new laptop .. try to repeat them

**Comment by Grizzly-Adam** [comment]
Fresh install, new world, new computers. Have to click/type mail twice to run it. Opens fine the second time. Shut off the computer, and its back to having to run it twice.

**Comment by bell07** [comment]
Yes, found if. Fresh booted computer have the issue too. The "last player" info is missed at first try so the app closes automatically for security reason, because the player unknown)

**Comment by Grizzly-Adam** [comment]
Sweet!

**Comment by bell07** [comment]
I did some changes on mail app to solve it (last_player is now current_player in most cases). I know you did some changes on this app too for theming. Can you upload your version so I can merge them together?

**Comment by Grizzly-Adam** [comment]
My latest version is in my git, in the more_theming _support branch.

https://github.com/Grizzly-Adam/minetest-laptop/tree/more_theming_support

**Comment by bell07** [comment]
Ok, created pull request to the upstream master and to your more_theming_support branch
#113 and https://github.com/Grizzly-Adam/minetest-laptop/pull/1

**Comment by bell07** [comment]
Which error? I tested it before creating the PR

**Comment by Grizzly-Adam** [comment]
Maybe you changed things in other files, I thought it was only the mail app
you changed so I only installed it. In csbos it says launched, in launcher
it does nothing.

**Comment by bell07** [comment]
You should not think in files but in changes ;) Of course I changed more files. The important change is in mtos.lua

**Comment by Grizzly-Adam** [comment]
Thanks. I will give it a quick go.

**Comment by Grizzly-Adam** [comment]
Works great on this end.
