### ISSUE TITLE
Bundle apps / Content

### ISSUE THREAD

**Issue by apachano** [Gerold55/minetest-laptop#118]
I was wondering if you guys have considered bundling the apps into . . . well bundles . . . 
What I mean is set up the apps for the mod like mods are for minetest. To install an app into the mod all you do is drop its folder into the apps folder and the mod searches for it. 
So the structure would be minetest-laptop -> apps -> calculator -> init.lua
Then each app folder also holds its textures making them easier to install and uninstall. 

This could also be done with textures and computers.

**Comment by bell07** [comment]
Possible only if we split the mod to a modpack with any app (or feature set like the printer/printing) is an own minetest mod. Then we can select on mod level which content should be active for laptop.

Gerold55 and Grizzly-Adam started with some "addition pack mods":
https://forum.minetest.net/viewtopic.php?f=9&t=19097
https://forum.minetest.net/viewtopic.php?f=9&t=19580
https://github.com/Grizzly-Adam/PCPack2

But inside of a mod we cannot separate textures, all textres needs to be placed to the one texture folder.

**Comment by apachano** [comment]
I've gotten the textures to load from other files in the past but really thinking about it I guess the textures folder exists for efficiency in its own.
