### ISSUE TITLE
All Themes Not Showing Up

### ISSUE THREAD

**Issue by Gerold55** [Gerold55/minetest-laptop#125]
As said above the themes aren't showing up when trying to change the theme.

**Comment by bell07** [comment]
Can you please add a screenshot what you mean?

**Comment by Gerold55** [comment]
![screenshot 370](https://user-images.githubusercontent.com/13843095/40404095-01c46bda-5e24-11e8-8099-bd801e8a4578.png)
![screenshot 371](https://user-images.githubusercontent.com/13843095/40404096-023ffe80-5e24-11e8-9d56-ad5dc5c90d22.png)
![Uploading Screenshot (372).png…]()

**Comment by bell07** [comment]
CrossOver uses os_version = "6.33",
Amber/Greenshell- Themes uses os_max_version = '5.50',
The most "modern" themes (like the cubic or snowpine) are os_min_version = '7.00',
So a lot of themes are not useable on CrossOver
