### ISSUE TITLE
Bug when trying to turn on computers

### ISSUE THREAD

**Issue by Manolo789** [Gerold55/minetest-laptop#146]
Hello.
When you try to turn on one of the computers, it happens to shut down immediately afterwards.
Attached is a video demonstrating the problem.

https://github.com/Gerold55/laptop/assets/92552607/971ef138-f2fc-4ca5-bc05-953189e21eaa

Minetest version: 5.8.0
Active renderer: OpenGL 4.6.0

**Comment by bell07** [comment]
@Manolo789 Do you see any messages in the minetest log files or console output?

Which game do you use? Tried shortly with Whynot, the issue does not appear for me

**Comment by bell07** [comment]
@Manolo789 , do you use any "technic" or "power_generators" mod? Maybe your laptops need to be connected to power in any way. I don not use the power enhancements.

**Comment by Manolo789** [comment]
Hello @bell07, I'm playing the minetest game. You were right, if I connect the computer to the 'technic' power supply, the computer starts to work. Problem solved :)
Attached is a video of the test I did when connecting the computer to the 'technic' electrical network.

https://github.com/Gerold55/laptop/assets/92552607/4265038e-d948-47a2-bdcb-195bb9569c38
