### ISSUE TITLE
Request: Change computer nodes with theme

### ISSUE THREAD

**Issue by v-rob** [Gerold55/minetest-laptop#34]
The computer nodes always have the same desktop background, regardless of which theme there is.  I suggest using ipairs in the laptop.register_hardware to make new nodes for each theme.  When the theme is changed, detect which computer it is and use os:swap_node to change it to the proper node.  The node textures would be specified in the theme.

**Comment by Gerold55** [comment]
How would you make it so that you don't have too many textures? Could it be a simple overlay of the theme texture on the computer node screen?

**Comment by v-rob** [comment]
I'm thinking about using meshnodes.  Meshnodes can have different planes that have different textures, so if you found someone who was good with Blender, then they could make the computers into meshnodes that look the same and have a separate texture for the screen.  This would reduce the number of textures from 6+ textures per node to one texture plus the screen, so only 2 textures per node.

**Comment by Gerold55** [comment]
Well I've been having trouble getting help with models. Maybe the "blurry" like theme that crossZover has done will do for now because it looks pretty good and you don't know which theme is being used.

**Comment by v-rob** [comment]
I'll see what I can do.  I might be able to do the models, but no promises.

**Comment by Gerold55** [comment]
If you can't do the models then that's ok. I'm working on a redo of the models that I made.

**Comment by bell07** [comment]
Please check if it is possible to change the texture at runtime on node (small hardcoded demo how it). My knowledge it is not possible, We can colorize with param2 (like unifieddyes), we can place an entity before node (like display_modpack) or we can add a hardware-node for each installed background. Except the color the both other solutions does overhead I do not like. Using colorize we can apply ambiente/base color to the node. But the node needs to support them (See homedecor beds for example)

**Comment by Gerold55** [comment]
Wouldn't the objs make this mod even bigger rather than just nodes?

**Comment by bell07** [comment]
Yes, the objs will be make mod bigger and more complicated. I do not like the idea because of synchronization is needed between node and object, the issues with /clearobjects, or worldedit cannot store/place the objects and so on :-(
In general, you need for each background/theme corresponding textures for the hardware, to many work.
And it looks still strange if an app is open but the display is still desktop :-/
We need leave the node still "symbolic". Maybe show "Screensaver" on node or just white screen?
Or just colored screen on node using the param2-coloring? So each theme can have "monitor_ambiente_color" attribute?

**Comment by Gerold55** [comment]
Is it possible to just color the screen? I think that the Fruit Zero's on screen (not launcher) looks fine to me :)

**Comment by bell07** [comment]
> Is it possible to just color the screen?
Yes, but I do not know how. Please look to the bed's from homedecor how it works.

**Comment by Gerold55** [comment]
Oh ok I will a little bit later

**Comment by bell07** [comment]
>     paramtype2 == "colorfacedir"
>     ^ Same as `facedir`, but with colors.
>       The first three bits of `param2` tells which color
>       is picked from the palette.
>       The palette should have 8 pixels.

I prepared in my master. The theme can define node_color = NUMBER - Assume 0-7?
I set the blue theme to 4 but I do not see any difference. I think the textures needs to have the palette?

**Comment by Gerold55** [comment]
How would a palette be done?

**Comment by bell07** [comment]
unifieddyes does have "universal" palettes https://github.com/minetest-mods/unifieddyes/tree/master/textures

I think we can/need to create own palette-texture. But for the first I try to get any reaction using mentioned textures

**Comment by bell07** [comment]
I get it working!
Implemented only for laptop:laptop and blue theme as example. If you select the "Blue" theme on "laptop v2.0" the color is red.

Now it is for you, to create own palette, the unifieddyes_palette_redviolets.png needs to be replaced, to assign each theme an color number and configure other hardware to use the colors on enabled node

**Comment by bell07** [comment]
The enhancements to use the paramtype2 == "colorfacedir" is in the upstream master.
To use it some work on node definition and textures required. Basically we need the palette texture with colors so we can assign the color number for each theme. Does anyone work on this?

**Comment by bell07** [comment]
@Grizzly-Adam do you see any use for this enhancement? It is possible to colorize some textures on hardware based on theme. Feature is already in upstream master, but unused.
I had a small working demo, reverted before merging : See reverted changes on laptop:laptop in https://github.com/Gerold55/minetest-laptop/commit/6701aec88f7ff1d0faaaf69ed3556f103c869261

Note, the node_color value is a "palette-value" from palette file 
`def.palette = "unifieddyes_palette_redviolets.png" --TODO: Replace by own laptop specific PNG file`
We need also own palette file if we like to use the feature

**Comment by Grizzly-Adam** [comment]
I can't think of a reason for this.

**Comment by bell07** [comment]
The basic idea was to show theme background on hardware node. But it is not possible without entity-woodo. Therefore this was a compromis

@Gerold55 can we delete the unifieddyes_palette_redviolets.png file and close this issue?

**Comment by Gerold55** [comment]
I believe that this can be deleted I have no idea what texture you're talking about though.
