### ISSUE TITLE
Merges

### ISSUE THREAD

**Issue by Gerold55** [Gerold55/minetest-laptop#37]
All of us need to check at least once a day for updates on everyone's fork/the main github page so we all are at the same update. On the forums, Bell07's github fork is considered as a beta page. So any updates done there can be merged to other forks/the main page if they work 100% :) I hope everyone understands Thanks. @bell07 @v-rob

**Comment by bell07** [comment]
Git methodology is to use master branch for stable things and EACH new thing is in own branch till it is stable enough to be merged to the master.

My master is MY repository. The way is:
1. I develop on my master repo at home (not public/github)
2. If I think it kan be shown to other dev's I push them to MY master
3. If I think I am finished I create a new branch with pull request, based on your "Upstream"-Master
4. If my work is finished but anything other is still missed, you create a new branch on your "Upstream repo" and merge my changes to this branch
5. If you think all it is fine you merges them to your master

I know, previous I created directly PR using the master branch, that was wrong
https://guides.github.com/introduction/flow/

**Comment by Gerold55** [comment]
@bell07 I've been trying to send a pull request to your fork and it's not allowing me to.

**Comment by bell07** [comment]
You are the upstream ;)
If I see something new in upstream master I can merge it without pull requests.

Git is not a versionscontrol but source manager. In git yo do not push changes. A pull request is just a proposal to merge. But the repo-owner can decide what he need to merge.

My primary reop is local on development PC at home. During development If I see something new in your master I merge it to this local repo. Later, if I like something to publish I push it to my repo at github. my github master is just for information, I accept no pull request to them because I am not upstream.

**Comment by Gerold55** [comment]
Oh ok 👍

**Comment by Gerold55** [comment]
For future reference you submitting changes without a pull request is 100% fine as long as what you submit is complete and all bugs are worked out.

**Comment by bell07** [comment]
Usually I create pull request for review. If I am sure the change is ok (small bugfix) I push it directly because you gived me authorization. So if you get a pull request from me, please test the changes before merging. If something is missed or wrong I can change it directly to the same PR, so the PR should be open till all related things are done.

For examlpe: I did a pull request for old-computer-launcher with info the image is still missed. The right way is to provide the image and then merge thhe PR. It is not a problem if a PR is open for long time

**Comment by bell07** [comment]
.. in other words: a PR is like an "Issue" but directly connected to a branch with related changes...

**Comment by Gerold55** [comment]
The launcher old PC icon is done. And has been added to my repo

**Comment by bell07** [comment]
I seen that. But I am not at home this week, therefore you do not see any changes in my repo.

**Comment by bell07** [comment]
Maybe some informations about git and github in general:
https://betterexplained.com/articles/aha-moments-when-learning-git/
https://hackernoon.com/understanding-git-fcffd87c15a3

Windows and mac users can use the github app: https://desktop.github.com/
Windows user only have the https://tortoisegit.org/
Linux: The best way: CLI ;-)

**Comment by bell07** [comment]
I opened "Issues" in my repo for engine related issues. And for not finished apps developed by me. Related pull requests I will check and accept

**Comment by Gerold55** [comment]
What are the issues?

**Comment by bell07** [comment]
I meant the issues related to my WIP development that is not in your upstream master

**Comment by Gerold55** [comment]
Other than I think the calculator needs to be centered looks ok to me.

**Comment by Gerold55** [comment]
Also can the calculator image be realigned? It looks a tad stretched.

**Comment by bell07** [comment]
You mean the calculator texture in launcher? Feel free to edit the texture.
I did set up the pull request for all my last changes

**Comment by bell07** [comment]
@Gerold55, please do not upload my not finished work to your master. The master should be "stable version". You can create an new branch (dev?) for not completed changes.

The second issue is my git commit history is lost if you just uploads my files using "github upload". You can create PR from my master to your dev branch and merge them, if you still do not like to use an git or github client

**Comment by Gerold55** [comment]
I haven't pulled anything from your repo. I just wait til you submit a pull request.

**Comment by bell07** [comment]
I am about https://github.com/Gerold55/laptop/commit/318c126359dc54d524d492726620ea234def1eaa, https://github.com/Gerold55/laptop/commit/0a2c8d6e3701b0805915c0388897382a6bebf0ae,  https://github.com/Gerold55/laptop/commit/db8886ef3b0d89857b471bd3d96b4d1a42119b80 and https://github.com/Gerold55/laptop/commit/179cf2e6a083ce9b48845b8a31fc43a74462c36d

You gived me permission to write to your repo, so will reset your master to before this commits and create a new "devel" branch with my changes. So you can upload files related to incomplete features to this branch

**Comment by bell07** [comment]
Do we still need the development branch? At the time it is mirrored master from my fork.
I plan to carry out to take own branch/PR for each enhancement as usual in the git world. So the goal-less "development" branch is not really necessary.
So my proposal is to remove again the development branch. @Gerold55, if you like to create a pull requst to my branch, you can create a new branch based on your master and upload files to this one. https://help.github.com/articles/creating-and-deleting-branches-within-your-repository/

**Comment by bell07** [comment]
Can we close this issue? I think the discussion is done

**Comment by bell07** [comment]
Removed the "development" branch. For now each enhancement should have own branch until then develompent is finished and ready to be merged in master. This is the usual method in git.
