### ISSUE TITLE
Printer

### ISSUE THREAD

**Issue by Gerold55** [Gerold55/minetest-laptop#38]
Have been working on a printer model and textures with @CrossZover. Any ideas on what it should do in the future?

bell07: WiP status
- [X] Printer hardware
- [X] Print button in text app
- [x] Print button in email app
- [X] mtos:print_file_dialog() Method
- [X] Print settings screen
- [X] Scan for printers nearby
- [x]  Print preview
- [X] Move text to printer queue
- [X] Printer queue and output tray view
- [X] Input tray: Fill printer with paper and dye
- [X] Paper item with show printed text
- [x] Ability to cancel prints via settings menu (printer settings)

**Comment by bell07** [comment]
My idea to the printer:
It should be registered in framework as "hardware" with custom launcher.
The custom launcher is the "Printer-OS" that cannot start any other apps but manages a printer queue. The floppy-slot (Todo) is a paper slot, accept a paper- or a book item as medium. If inserted a text-document from queue and write it to the item meta. How the written item should be readable, this idea is still missed (Own formspec on use item?)

The "Modern-OS" needs a "printer driver" means an app that is able to seach for nearly printers and be able to store text documents to the printer queue. Maybe the start of Printer-OS-launcher-app as "normal-app" remote possible.

Again a lot of work. For the first maybe an simple launcher with "Paper Jam" error screen like the old computer at the time?

**Comment by bell07** [comment]
For empty paper I plan to use the paper from minetest_game / default mod. But we need a new item for printed paper. I plan to add a on_use formspec to show the printed content.

**Comment by bell07** [comment]
I seen on screenshot there is a printer. Can you please provide the Printer-"Hardware" to the development branch? So I can start to write the OS for them.
Second thing I need a texture for "printed paper" item that will be the printer's output.

**Comment by bell07** [comment]
I wrote the WiP status for planned changes in the first post for tracking and to collect additional idea. The flagged points are already in development branch.
For graphics I need a "printed paper" item texture, something like the default:paper, because I plan to use default:paper for input

**Comment by Gerold55** [comment]
![printer_paper](https://user-images.githubusercontent.com/13843095/34275012-6244f818-e669-11e7-8dd9-c3c48cc97c77.png)

How does that look?

**Comment by bell07** [comment]
I am about the item. This one: https://github.com/minetest/minetest_game/blob/master/mods/default/textures/default_paper.png but printed

**Comment by Gerold55** [comment]
How's this?
![1 1](https://user-images.githubusercontent.com/13843095/34285200-ccfb81d6-e6a5-11e7-962d-ca9d6ebe4310.png)

**Comment by bell07** [comment]
Ok, please add it to development branch. I should see how it looks as item, thanks

**Comment by Gerold55** [comment]
Uploaded.

**Comment by Gerold55** [comment]
@bell07 what do I need to change to move the print countdown over and to shrink it slightly? And to add a different texture?

**Comment by bell07** [comment]
The previous print countdown was a quick&dirty hack. Now I did some formspec rewrites on printer launcher, added "reset" (=delete all jobs) and "delete" (=delete 1st job) buttons and moved the countdown to own element using the red button texture:
[Line 120](https://github.com/Gerold55/minetest-laptop/blob/development/apps/os_print_app.lua#L120): `"background[3.7,3.1;"..(mtos.sysdata.print_progress)..",0.5;laptop_theme_red_back_button.png]"`
I think you can read the lua in the meantime ;-)

**Comment by bell07** [comment]
Is still something to do for printer or should I prepare a PR to master? From technical point of view the development is finished. Maybe the formspecs are a bit chunky but if no one like to do it more pretty we should add them to master as is. Maybe anyone do it pretty in the feature.
