### ISSUE TITLE
app-request: Arcade tetris emulator

### ISSUE THREAD

**Issue by bell07** [Gerold55/minetest-laptop#41]
Port https://github.com/minetest-mods/homedecor_modpack/blob/master/computer/tetris.lua to own app called "Tetris Arcade emulator" ...

**Comment by Gerold55** [comment]
Couldn't the Tetris pieces be made up out of wool?

**Comment by bell07** [comment]
Sure, and good point. I do not like to copy textures from homedecor mod to laptop mod. So we need own textures. Or we just use the wool textures.

**Comment by Gerold55** [comment]
Or just a single white texture and colorize it in the code or something like that. But we can test different textures out and see which one fits together.

**Comment by bell07** [comment]
First draft in my master and in your development branch ...

**Comment by Gerold55** [comment]
Should we try to use colored blocks instead of wool? Or make the wool a bit tighter together?

**Comment by bell07** [comment]
It's possible to use 1 white texture and colorize them using color codes. I like the idea to remove the wool and use colorized texture

**Comment by Gerold55** [comment]
I believe that one of the textures used is only white.

**Comment by bell07** [comment]
Can you work on texture replacement? Or provide the white texture name and #RGB values for coloring?

**Comment by Gerold55** [comment]
Laptop_fruit_base.png

**Comment by bell07** [comment]
I used the diamond-block from default mod because of looks beter. The visual is ok for me for now.
If you like to do some additional adjustments, just edit and play around the next values in file tetris_app.lua
```
local base_color_texture = "default_diamond_block.png"
local base_color_alpha = '128'
local sizex, sizey, size = 0.42, 0.44, 0.47
```

The board background is defined at bottom in 
`return 'container[3,1]background[0,-0.05;4.35,9;'.. mtos.theme.contrast_bg....`
Just edit the 4.35 (width) and 9 (high).

**Comment by bell07** [comment]
The game launcher icon is missed also. Can you create one? If the launcher icon is done and the current app state is ok for you, I can prepare the pull request. This time merging development is not the best way because some printer files already in development that should not be to master at the time.

**Comment by Gerold55** [comment]
Ok I'll take a look at it soon.

**Comment by Gerold55** [comment]
Looks ok to me and the community. @kingoscarsgames is working on an icon for it.

**Comment by bell07** [comment]
Ok, if I am afk and the icon is done, I prepared the branch "pr_tetris"
https://github.com/Gerold55/minetest-laptop/compare/master...bell07:pr_tetris
you can merge and adjust to use the new icon. Of course you can adjust the labels. Unsure if the "Arcade tetris emulator" is still a god name

**Comment by bell07** [comment]
merged
