### ISSUE TITLE
Concepts and Ideas

### ISSUE THREAD

**Issue by Gerold55** [Gerold55/minetest-laptop#45]
![screenshot 133](https://user-images.githubusercontent.com/13843095/33800703-c1b3fff6-dd13-11e7-9149-6d96407c752a.png)

**Comment by Gerold55** [comment]
![email](https://user-images.githubusercontent.com/13843095/33800723-21769dc2-dd14-11e7-8c95-ae1cf1db911f.png)

**Comment by bell07** [comment]
What is the goal for this issue? Each issue needs a goal to be closed

**Comment by bell07** [comment]
Issue without any goal
