### ISSUE TITLE
Received and Sent Emails

### ISSUE THREAD

**Issue by Gerold55** [Gerold55/minetest-laptop#51]
Received and Sent Emails are editable when looking at them is it possible to fix that?

**Comment by Gerold55** [comment]
![gui_formbg](https://user-images.githubusercontent.com/13843095/33922299-dba7c024-df97-11e7-9119-d138ae811812.png)
Can you add this texture in instead of the gray background?

**Comment by bell07** [comment]
Please re-label. It is not a bug.

Unsure if this texture can be applied for all themes.
We can try it to add to the sticky notepad app at the first. Just replace the "gui_formbg.png" by your file in stickynote_app.lua. I cannot do all lua changes byself. Fear you need to learn some lua basics ;-)

**Comment by bell07** [comment]
hm, the texture without the border can be used for "printed paper" in #38 ?

**Comment by Crosszover** [comment]
![gui_formbg2](https://user-images.githubusercontent.com/33940608/33952240-95738b18-e007-11e7-95d7-7be94af24e9a.png)
i suggest this to try, it's more clean..

**Comment by Gerold55** [comment]
It's supposed to be gray?

**Comment by bell07** [comment]
Maybe new "contrast_background" setting in themes with the gray in default?

**Comment by Gerold55** [comment]
![screenshot 147](https://user-images.githubusercontent.com/13843095/33954708-15fa08ee-e007-11e7-9b2b-56142b1ead3c.png)
Can you add the icon for that button?

**Comment by bell07** [comment]
> Received and Sent Emails are editable when looking at them is it possible to fix that?

There is no read-only multiline element in formspec at the time. Therefore no.
But the changes are not saved so it is just cosmetic issue

> Can you add the icon for that button?

We need 2x icons, for "Switch to inbox" and for "Switch to sentbox"

**Comment by Gerold55** [comment]
Also is it possible to add the sent icon for the send message button? What exactly is needed for "2x" icons?

**Comment by bell07** [comment]
On screenshot the "Sentbox" is visible, means "Switch to sentbox". If you press them and are in the sentbox the button is "Inbox" means "switch back to inbox". Both button states needs own icon

**Comment by Gerold55** [comment]
Oh ok I'll see what can be done.

**Comment by Gerold55** [comment]
Those icons are already available. 
Sent icon = laptop_mail_sentbox.png
Inbox icon = laptop_mail_received.png

**Comment by bell07** [comment]
The themes support the Parameter "contrast_bg". 
At the time it is the just the default gray "gui_formbg.png" for all themes.
Is anyone working on contrast-backgrounds for each theme? The gray could be in basic theme and colorized in other theme.

**Comment by bell07** [comment]
Further discussion about the color and background for textarea in #85
