### ISSUE TITLE
USB transfer

### ISSUE THREAD

**Issue by Gerold55** [Gerold55/minetest-laptop#58]
When you transfer the USB from one laptop to another you don't see the saved data that's on the flash drive.

**Comment by bell07** [comment]
How you like to see the saved data? It is like real floppy/usb-stick with proprietary data image format.
You can write a label to the usb-stick to be able to know what is backed up to the stick

**Comment by Gerold55** [comment]
So you can't leave it say the USB Storage?

**Comment by Gerold55** [comment]
I'll take another look at it.

**Comment by bell07** [comment]
The HDD storage is dumped to the USB storage without any data interpretation. It is like a "partition image". If you do not give a proper label you cannot see inside

**Comment by Gerold55** [comment]
Oh ok

**Comment by bell07** [comment]
Maybe I did not understand the question? Are you about "backup" or are you about stored texts?

**Comment by Gerold55** [comment]
To be able to not have to rename the USB to transfer should/could be an option. ☺

**Comment by bell07** [comment]
This was not the answer for my question ;-)
If you about the backup: Maybe auto-renaming usb to "Backup disk of "..hardware_name ?

**Comment by Gerold55** [comment]
Could do that when you click data boot and backup. Or that person can put own custom name onto the USB

**Comment by bell07** [comment]
You are right. Rename it during formatting for each format will be nice.
backup: "Backup disk of "..hardware_name .. " from " .. systemdate
data: "Data " .. itemname
boot: "OldOS boot disk"
?
