### ISSUE TITLE
app-request: Browser

### ISSUE THREAD

**Issue by Gerold55** [Gerold55/minetest-laptop#67]
The browser is where you have different icons for different help pages. First one would be for the "wiki" for the laptop mod.

**Comment by bell07** [comment]
Is there a difference to #48 ? If not, can we close this issue?

**Comment by Gerold55** [comment]
This is sort of like an internet browser.

**Comment by Gerold55** [comment]
@bell07 @Grizzly-Adam could we start working on this after themes is done?

**Comment by Grizzly-Adam** [comment]
So what are we looking at, building our own internet?

**Comment by Gerold55** [comment]
Sort of. It should sorta be text-based probably. We should have a wiki and some other things in it. Not really a full-fledged internet browser like google.

**Comment by bell07** [comment]
Agre to Grizzly-Adam. The issue is the content to fill the own internet.
Somehow needs to write the wiki content and the content of "some other things" at the first.

THe ingame writing is bad idea because we can store data for each world only, So each singleplayer/each server/each world starts with empty WWW.

THe other issue is the formspec limitations. The "Stickynote pad" is nearly the maximum posiible for ingame authoring. :-(

**Comment by Gerold55** [comment]
Well for the web browser it would be more of text base and we can set it up
to have the ability to make the pages outside of the game in the code/mod.
We can also have our own site names. The main page could be a welcome page
possibly.

**Comment by Gerold55** [comment]
So it won't access the real internet but our own made up one.

**Comment by bell07** [comment]
I like to move the "Ingame documentation" discussion to this thread. The browser could be used for ingame documentation too. (visiting CS-BOS homepage?)

Draft prototype / tech demo exists in my [docu_app branch](https://github.com/bell07/minetest-laptop/tree/docu_app) branch. Simple app that reads text file from mod directory.

**Comment by Gerold55** [comment]
Sounds good to me 👍

**Comment by Grizzly-Adam** [comment]
@bell07 How do we plan to support links? 
I think the web needs to be done primarily in addons-- in a method easy for the average Joe to do. We put our documentation in the main build, and everything else in addons to keep the size small and the internet modular. Added bonus-- it will be more like the real internet if we can get people to write their own sites. 

I could include a website in my BBQ mod for instance that talks about BBQ and tells about the grills, etc.

**Comment by bell07** [comment]
Links, hm, no idea. At the end the very basic version is a "text file viewer" with some navigation buttons. How the navigation buttons should be defined is unclear at the time.

The handling is more like the skins at the time: Server owner puts texts (www-pages) files to an folder, the player can look for.

That is my idea. I see a lot of work for to get small ingame value, so I am not motivated to write it.

> I could include a website in my BBQ mod for instance that talks about BBQ and tells about the grills, etc.

The right way for ingame documentation is to write factoids for wuzzy's doc system. Because it is usable for people without laptop too.
https://forum.minetest.net/viewtopic.php?t=15912

Maybe the browser can show the help, but small ingame value only, because the player can allways look to the documentation from player inventory.

**Comment by Gerold55** [comment]
Well, I think it should be available both ways. The browser would have "text files" but you can type some made up site and the site would be defined in some way or another. The individual can add more sites to the laptop mod. Also, we can use it for servers like Persistent Kingdoms and each time can see who's on the team and what's going on.

**Comment by bell07** [comment]
> Well, I think it should be available both ways. The browser would have "text files" but you can type some made up site and the site would be defined in some way or another. The individual can add more sites to the laptop mod.

At the first we need to differentiate the "text files" (Sticky note app) and "text files" (Real life *.txt files on server). My proposal is to support the second at the first.

The stickynote supports HDD and FDD storage at the time only. As I implemented it I decided not to use the cloud. Using cloud it could be possible to store documents to "private storage cloud (accessable by user)", public storage cloud (accessably by all players) and if "Teams" are implemented, the team storage cloud). I decided not to use it because then tere is no reason anymore to store anything on HDD or removeable.

Maybe we find an way to "upload" stickynote text files to the WWW. But this should not be easy as the "save as". 

> Also, we can use it for servers like Persistent Kingdoms and each time can see who's on the team and what's going on.

Team support is missed complelty, requested in #116 
Maybe the mail app can support the teams at the first to inform all members what's going on

**Comment by Gerold55** [comment]
@bell07 how would I start to work on this? I'm wanting to create individual formspecs for each website.

**Comment by bell07** [comment]
The best way you write an own app each website at the first. using `laptop.register_app()`
Second step you can implement an "overview" app that contains links to the web-pages using buttons.
The navigation can be done in receive_fields_func using `mtos:set_app(appname)`
If this is working, you can change register_app to register_view - technically the same but not in launcher

**Comment by bell07** [comment]
Pls. do not merge your changes directly to master. Pls. create a new branch "browser_app" for this. Usually only reviewed and well-tested changes should be merged to master. All in progress-changes should be in own branch

**Comment by Gerold55** [comment]
Am not too sure what to do from here @bell07

**Comment by bell07** [comment]
You need a formspec at the next

```
app_info = "Web Browser",
	formspec_func = function(app, mtos)
		local formspec = mtos.theme:get_label('0,0', 'Hello World')..
		return formspec
	end,
```

**Comment by bell07** [comment]
You can just concatenate the formspec strings as in other mods, but if a theme method exists, please use the method because of automatically theme applied

**Comment by Gerold55** [comment]
I'm gonna figure it out hopefully I can lol

**Comment by Gerold55** [comment]
@bell07 how would I create a search bar? I can't find that anywhere.

**Comment by Gerold55** [comment]
So I've got a text field just need a little help with getting it to function.

**Comment by Gerold55** [comment]
![screenshot 369](https://user-images.githubusercontent.com/13843095/40402928-6ea7c0c4-5e1c-11e8-8ea4-e4f2174597f5.png)

**Comment by bell07** [comment]
The next step is to add the
```
	receive_fields_func = function(app, mtos, sender, fields)
		
	end, 
```
The fields table contains your input and pressed buttons, based on definition in formspec_func. Can you please copy@paste your current code? (`in code-tags`, no screenshot)

if you start minetest from console you can check the content adding temporary the print(dump(fields))) into the function

**Comment by Gerold55** [comment]
`laptop.register_app("browser", {
	app_name = "MineBrowse",
	app_icon = "laptop_removable.png",
	app_info = "Web Browser",
	formspec_func = function(app, mtos)
		local formspec = 
				"field[.2,.5;13,1;name; ;]"..
				"image_button[12.9,.3;.8,.8;laptop_theme_basic_button.png;name;]"..
				"image_button[13.6,.3;.8,.8;laptop_theme_basic_button.png;name;]"..
				"image_button[14.3,.3;.8,.8;laptop_theme_basic_button.png;name;]"..
				']'
		return formspec
	end,
})`

**Comment by bell07** [comment]
1. ok, you need different "name"'s at the first. So you can access them using fields.name in receive_fields_func.
2. For buttons they are themed methods `get_button()` and `get_image_button()`
3. the laset ']' is not needed

Untested:
```
	formspec_func = function(app, mtos)
		local formspec = 
			"field[.2,.5;13,1;input_field; ;]field_close_on_enter[input_field;false]"..
			mtos.theme:get_image_button('12.9,.3;.8,.8', 'minor', 'xxx_button', 'laptop_theme_basic_button.png', '', 'XXX Tooltipp')
		return formspec
	end,
	receive_fields_func = function(app, mtos, sender, fields)
		if fields.key_enter then
			print("Enter pressed, the Input field contains "..fields.input_field)
		elseif fields.xxx_button then
			print("XXX Button pressed")
		end
	end, 
```

You can also look to other apps how anything is done

**Comment by Gerold55** [comment]
So how would I add 2 additional buttons to it? Also, I'm wanting it to switch by looking for the website URL. So when you type it in it'll take you to that address. Also when you open it up it should automatically be opened to the main webpage.

**Comment by Gerold55** [comment]
@bell07 I'm sry not used to making something like this so that's why I'm asking so many questions.

**Comment by Gerold55** [comment]
![screenshot 373](https://user-images.githubusercontent.com/13843095/40450527-fab58bf4-5ea9-11e8-8999-95858e7fc9fd.png)
![screenshot 374](https://user-images.githubusercontent.com/13843095/40450528-fb4ab1ca-5ea9-11e8-8806-b10f42645ac2.png)

**Comment by Gerold55** [comment]
![screenshot 378](https://user-images.githubusercontent.com/13843095/40465224-a9a9144e-5eed-11e8-9ea3-3235e318f23b.png)

Here's what I have so far. Needs some further kinking out but this is the basis of the welcome page. Let me know if you have any further ideas for it.

**Comment by Gerold55** [comment]
[browser_app.zip](https://github.com/Gerold55/minetest-laptop/files/2033877/browser_app.zip)

**Comment by Gerold55** [comment]
@bell07

**Comment by Gerold55** [comment]
Hopefully we can get it working. So I've added a few additional things to the app which differs from the app I linked above.

**Comment by bell07** [comment]
Sorry, but I am not 24h at computer.

I created a new branch for you and uploaded your file to the [browser_app](https://github.com/Gerold55/minetest-laptop/tree/browser_app) branch.

Please do all browser app related work to this branch. This way it is possible just to merge all changes to master using pull request, if all is done.

Tested shortly. The Images laptop_welcome_web.png and laptop_background_web.png are missed. Please upload the images to the mentioned branch. If you have updated the lua file in the meantime, so please update it in branch too.

Do you need any help from my site?

**Comment by Gerold55** [comment]
I need help getting the buttons to work so it can switch between websites when typed in (URL). I was hoping you could possibly help with that.

**Comment by bell07** [comment]
I have some time in ~4 h. If you did some changes in the meantime, please update the branch..
The links should be buttons, we need new prefix „url“ so the buttons looks like link text. I can do the template in default theme, but all themes needs to be enhanced for new prefix...

**Comment by Gerold55** [comment]
Is there a way to detect a website that has been added and it'll create a link or something? I'm also wanting to add an area where it'll have a list of websites that are appropriate.

**Comment by bell07** [comment]
I started some framework working.
My current concept is each Website is just an App-View, not shown in launcher. A list of websites is possible, like the main launcher lists all "Normal" apps. 
Unfortunatelly it is not possible to "Submit a Website". Each Website needs to be registered from installed mod.

**Comment by Gerold55** [comment]
The submit a website button will take them to submit.official page where
they can submit a website by visiting the site listed on their rl browser.

Brandon Chaney

**Comment by bell07** [comment]
I uploaded updated version now to the branch. Please note, the "themes.lua" is updated too, **so pls update your local working copy with both files** (or checkout full copy, or use git ;-))

The app does have is a working navigation, the pages list and some dummy pages. So feel free to fill the pages with content.

The themes.lua contains new default settings:

```
		-- used in browser app
		url_dark_textcolor = "#6495ED",
		url_dark_button = "laptop_theme_desktop_icon_label_button_black.png",
		url_bright_textcolor = "#000080",
		url_bright_button = "laptop_fruit_base.png",
```
New links could be url_dark or url_bright (depending on background) for now
`mtos.theme:get_button('x,y', 'url_dark', 'page_link', 'link.to.page')`

**Comment by bell07** [comment]
Updated API documentation and set min_version to value the old CS_BOS computers cannot execute this app

> The submit a website button will take them to submit.official page where
> they can submit a website by visiting the site listed on their rl browser.

Realized. There is a submit.official scaffold in file you can fill with informations about RL-pages and how to contrubute

**Comment by Gerold55** [comment]
Also is there a way to make it so when you open up the browser it shows the URL of the page that you're on which is welcome.official.

**Comment by Gerold55** [comment]
[browser_app.zip](https://github.com/Gerold55/minetest-laptop/files/2040975/browser_app.zip)
Here's the new app with my small updates because idk if you have edited the code again.

**Comment by bell07** [comment]
About your change:
`mtos.theme:get_image_button('12.9,.3;.8,.8', 'minor', 'go_button', 'laptop_theme_basic_button.png^laptop_go_web.png', '', 'Go') ..`

"minor" contains already "laptop_theme_minor_button.png" that you override by both other textures. The "minor" is not the right settings prefix. I think we need a new prefix "toolbar" ?
Just replace minor by toolbar and add toolbar_textcolor = #RGBCOLOR and toolbar_button= "laptop_theme_basic_button.png" settings to the defaults in themes.lua

**Comment by Gerold55** [comment]
Could we make it possible to be able to load websites from different files. So people can create their own website and then put it into a website folder and the browser will pick it up?

**Comment by bell07** [comment]
Merged your last changes with toolbar buttons, with adjustments. Introduced "toolbar" color-prefix.
Please update your local copy (3 changed files in commit)

**Comment by Gerold55** [comment]
How would I get the button at the bottom of the page to work?

**Comment by bell07** [comment]
Did additional move in code, so navigation to buttons with code "url_bright" works without additional implementation to destination in text.

Changed the link to `mtos.theme:get_button('11.3,9.3;3,.8', 'url_bright', 'page_link', 'submit.official') `
Note: "url_bright" is one of more possible visual prefixes. You can use 'url_black', or any other like 'minor', 'major', toolbar'. Look to API.md file for more informations.
'page_link' is fixed for navigation link button
The last parameter needs to match the "app-name" for of the page.

Restrictions:
No describable links
No tooltipps for links
To get both is is possible, but requires more development skills

**Comment by Gerold55** [comment]
![tablet](https://user-images.githubusercontent.com/13843095/40579790-ebbe8cbc-60fd-11e8-9a4d-2f967cc3d9b1.png)
This screenshot is from the MT for android. Is there any way to fix it?

**Comment by bell07** [comment]
What is the issue? THe text overlaps because the resolution is less then text. On your windows you can start the minetest in window mode and then resize the window. You see the issue appears for some low resolution. We cannot do anythong to avoid it. Less text to the line looks strange on high-resolution screens. Maybe try th multiline textarea[] element  for long texts to avoid the issue?

**Comment by Gerold55** [comment]
@bell07 do you have an example for a website that's not built into the text app because a number of people are confused.

**Comment by bell07** [comment]
No, but you can just move the "submit.official" to an own file for example (untested, I am not at home)
Move the code to new file `apps/browser_page_submit_app.lua`
```
--------------------------------------------
-- Submit informations
--------------------------------------------
laptop.register_view("submit.official", {
	app_info = "Contribute to Minetest Laptop Mod",
	browser_page = true,
	formspec_func = function(app, mtos)
		local formspec = laptop.browser_api.header_formspec_func(app, mtos) ..
			mtos.theme:get_label('.3,1.1','Hello submitted World!')
		return formspec
	end,
	receive_fields_func = function(app, mtos, sender, fields)
		laptop.browser_api.header_receive_fields_func(app, mtos, sender, fields)
	end
})
```

and delete the code from browser_app.lua

**Comment by Gerold55** [comment]
![options](https://user-images.githubusercontent.com/13843095/41207542-ec8975a0-6ce5-11e8-8bf8-d5df5cb52a4e.png)
@bell07

**Comment by Gerold55** [comment]
The ability to make the websites in game and using https API to use/pull from GitHub if that's possible

**Comment by bell07** [comment]
Bad idea. Automatically download and execute any code from any source is security hole for server host

**Comment by Gerold55** [comment]
Is there any way to make it more secure?

**Comment by Gerold55** [comment]
Also is there any way to create a website template that's not a part of the main file/app?

**Comment by bell07** [comment]
> Is there any way to make it more secure?

Then we cannot use lua for pages and need any Hyper-Text-Markup-Language and an interpreter for the new HTML-dialect.

I do not see the benefit for online updates:
- We cannot add new images ingame, text only (technical limitation)
- We need an ingame page editor - that cannot be more comfortable then notepad
- We need to require the git-client installation on any server that need to use the feature - As I understand you the git-client is an No-Go for you
- Any contributor need an github client

Summary - it is more easier to contribute to the project outsite the game

**Comment by bell07** [comment]
> Also is there any way to create a website template that's not a part of the main file/app?

As wrote already

> Move the code to new file `apps/browser_page_submit_app.lua`
> ```
> --------------------------------------------
> -- Submit informations
> --------------------------------------------
> laptop.register_view("submit.official", {
> 	app_info = "Contribute to Minetest Laptop Mod",
> 	browser_page = true,
> 	formspec_func = function(app, mtos)
> 		local formspec = laptop.browser_api.header_formspec_func(app, mtos) ..
> 			mtos.theme:get_label('.3,1.1','Hello submitted World!')
> 		return formspec
> 	end,
> 	receive_fields_func = function(app, mtos, sender, fields)
> 		laptop.browser_api.header_receive_fields_func(app, mtos, sender, fields)
> 	end
> })
> ```
> 
> and delete the code from browser_app.lua

Then you get a website template called "submit.official" outsite the main app file

**Comment by Gerold55** [comment]
Is there a way to leave out certain page links from websites available?

**Comment by Gerold55** [comment]
Can we get the text in the URL area to be black?

**Comment by bell07** [comment]
Use url_dark instead of url_bright

**Comment by Gerold55** [comment]
How would I do that with a field? I've tried something similar and didn't seem to work

**Comment by bell07** [comment]
I cannot say what is the best way without knowing what you like to do.
Note, the get_label does supporte the color prefixes too. If an label should look like a URL, use the url_bright (=bright background / dark foreground)  prefix.
`mtos.theme:get_label(area, label, color_prefix)`

but I do not understand your issue, the default textcolor "color_prefix" is black. If an theme changes them, you need to respect it. I fear you mix up the theming and site content.

**Comment by Gerold55** [comment]
Well for the text area the font color is white with a white background

**Comment by bell07** [comment]
Changing colors for editable texts is not possible in current Minetest version. That is the reason why I added the “contrast” prefix, means dark background for not changeable white text in edit fields. See to the text app for example, or to new mail screen. Sorry

**Comment by Gerold55** [comment]
![screenshot 425](https://user-images.githubusercontent.com/13843095/41559758-08aba342-7313-11e8-9cf9-360266549926.png)
We have a problem somewhere in the lines of code. Are you able to fix it?

**Comment by bell07** [comment]
Look to debug.txt file for error message. Or start minetest from command line to look into console output

**Comment by Gerold55** [comment]
[debug.txt](https://github.com/Gerold55/minetest-laptop/files/2113114/debug.txt)

**Comment by bell07** [comment]
Did you looked to the file byself?

> Can't write to file at E:\minetest-0.4.16-win641\bin\..\cache\media\

Disk full or no write permission?

> Mod name conflict detected: "laptop"
> Will not load: E:\minetest-0.4.16-win641\bin\..\mods\computers\laptop
> Overridden by: E:\minetest-0.4.16-win641\bin\..\mods\laptop

You need to delete one of the both

**Comment by Gerold55** [comment]
So we should only have the main sites on the websites available page and not the subsites with them. Is it possible to do so?

**Comment by bell07** [comment]
`if def.browser_page and mtos:is_app_compatible(name) then`

browser_page is checked in browser_api.navigate too, so you need an new view attribute "browser_main_page" ? Just add a new attribute the the "if" statement and to the pages definitions

`if def.browser_page and def.browser_main_page and mtos:is_app_compatible(name) then`

```
laptop.register_view("submit.official", {
	app_info = "Contribute to Minetest Laptop Mod",
	browser_page = true,
	browser_main_page = true,

```

**Comment by Gerold55** [comment]
It ain't working for me on my end idk what I am doing wrong :(
